// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rgtncfpulnvbzjbpxqbv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJndG5jZnB1bG52YnpqYnB4cWJ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTEwMTk4ODAsImV4cCI6MjA2NjU5NTg4MH0.SfgTIn5Mp9rkACaEg7cl8E3q2h3eL2lr2JyJzjEQlKQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);